[[proxies]]
name=""
# http proxy or socks5 proxy
url=""

[[proxies]]
name=""
url=""

[basic]
# http GET timeout, unit ms
timeout=3000
dest="https://www.google.com"
# check interval,unit second
interval=10

#retry count
retry=3
# after 'retrydelay' seconds,retry
retrydelay=3
[email]
apiServer=""
receiver=""
auth_key=""

[log]
level="debug"
logfile="/tmp/checkproxy.log"
showFullTime=true
reportCaller=false
