version: "3.9"
services:
  checkproxy:
    # build: .
    # ports:
    #   - "6070:8080"
    # environment:
    #   ALIDDNS_LOG_LEVEL: info
    image: sunliang711/checkproxy:master
    volumes:
      - ./config.toml:/usr/local/bin/config.toml

    restart: always
  
